# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.13-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir python-dotenv sqlalchemy
RUN pip install --no-cache-dir .

# Ensure Python output is not buffered
ENV PYTHONUNBUFFERED=1

# Start the MCP server
CMD ["python", "src/server.py"]
